version: "3.9"

services:
    mongo:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeME
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - ./deployment/mongoDB/:/docker-entrypoint-initdb.d/

    mongo-express:
        image: mongo-express:0.54
        restart: always
        ports:
            - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: changeME

    python:
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./:/app

    config-tool:
        build: ./deployment/configTool
        ports:
            - 4200:4200
