version: "3.9"

services:
    mongo:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeME
        ports:
            - 27017:27017
        volumes:
            - ./deployment/mongoDB/:/docker-entrypoint-initdb.d/

    mongo-express:
        image: mongo-express:0.54
        restart: always
        ports:
            - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: changeME

    ganache-cli:
        image: trufflesuite/ganache-cli:latest
        ports:
            - "8545:8545"
        entrypoint:
            - node
            - /app/ganache-core.docker.cli.js
            - --mnemonic
            - 'garbage maid chief stairs leader angry exclude extra green arrive buyer donor'
            - --hostname
            - '0.0.0.0'

    python:
        build: .
        ports:
            - 5000:5000

#     # config-tool:
#     #     build: ./deployment/configTool
#     #     ports:
#     #         - 5200:4200

    frontend:
        build: ./deployment/frontend
        ports:
            - 8080:80
